import type { KnipConfig } from "knip";

const config: KnipConfig = {
  workspaces: {
    "apps/frontend": {
      // Knip resolves Next.js and Vitest entry points on its own through their
      // plugins: only the entry points it cannot infer are listed here.
      entry: [
        // Run through `pnpm seed`, not imported by the app.
        "src/seed/index.ts",
      ],
      // Invoked by `.lintstagedrc.js` as a workspace binary rather than imported,
      // so Knip cannot trace it. The dependency is real: dropping it would break
      // formatting on commit.
      ignoreDependencies: ["prettier"],
      // Knip's Payload plugin loads `payload.config.ts` at analysis time, purely
      // to read the admin import map path from it. Loading that module builds the
      // Postgres adapter, whose connection pool holds an open handle: the event
      // loop never drains, Knip's own top-level await never settles and Node
      // aborts with exit code 13.
      //
      // The plugin only needs the import map, so it is given directly and the
      // config file is left out of `config`. Nothing is silenced — the entry
      // point below is exactly what the plugin would have derived, and
      // `payload.config.ts` is still analysed as ordinary source through the
      // Next.js plugin.
      payload: {
        config: [],
        entry: ["src/app/(payload)/admin/importMap.js"],
        // Repeated from the plugin's own defaults: overriding any of its keys
        // replaces the whole set, and these exclusions are what keep the
        // Payload-generated files out of the report. They are generated by the
        // CLI, not hand-written, so Knip has nothing useful to say about them.
        project: ["!src/migrations/**", "!src/payload-types.ts"],
      },
    },
    "packages/shared": {},
  },
};

export default config;
