// @ts-check
'use strict'

const { createNextConfig } = require('@portfolio/eslint-config/next')

module.exports = [
  // Files generated by the Payload CLI: any manual fix would be overwritten
  // at the next generation. Migrations are part of this — their content is
  // produced by `migrate:create` — but they stay reviewed and versioned,
  // since they describe the database schema.
  {
    ignores: ['src/app/(payload)/**', 'src/payload-types.ts', 'src/cms/migrations/**'],
  },
  ...createNextConfig({ tsconfigRootDir: __dirname }),
]
