/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    projects: Project
    experiences: Experience
    tags: Tag
    bookmarks: Bookmark
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    projects: ProjectsSelect<false> | ProjectsSelect<true>
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>
    tags: TagsSelect<false> | TagsSelect<true>
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    'site-identity': SiteIdentity
    profile: Profile
  }
  globalsSelect: {
    'site-identity': SiteIdentitySelect<false> | SiteIdentitySelect<true>
    profile: ProfileSelect<false> | ProfileSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  name: string
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * Renseignez l'URL : le titre, la description et l'image d'aperçu sont récupérés automatiquement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number
  /**
   * Adresse publique du projet, en https.
   */
  url: string
  /**
   * Laissez vide pour reprendre le titre de la page distante.
   */
  title?: string | null
  /**
   * Laissez vide pour reprendre la description de la page distante.
   */
  description?: string | null
  /**
   * Extraite des balises Open Graph à chaque modification de l'URL.
   */
  previewImageUrl?: string | null
  /**
   * Optionnel. Prend le pas sur l'image d'aperçu automatique quand il est renseigné.
   */
  cover?: (number | null) | Media
  /**
   * Optionnel. Affiché à côté du lien de démonstration.
   */
  repositoryUrl?: string | null
  /**
   * Affichées en surtitre de la carte projet.
   */
  technologies?: string[] | null
  featured?: boolean | null
  /**
   * Croissant : 0 en premier. À valeur égale, les projets les plus récents passent devant.
   */
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * Postes affichés sur la page À propos, du plus récent au plus ancien.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number
  company: string
  role: string
  location?: string | null
  /**
   * Sert au tri du parcours.
   */
  startDate: string
  /**
   * Laissez vide pour le poste en cours.
   */
  endDate?: string | null
  /**
   * Affiche « Aujourd’hui » à la place de la date de fin.
   */
  current?: boolean | null
  /**
   * Optionnel : le produit sur lequel porte la mission.
   */
  project?: string | null
  /**
   * Équipe, périmètre, enjeu de la mission.
   */
  context?: string | null
  achievements?:
    | {
        statement: string
        id?: string | null
      }[]
    | null
  technologies?: string[] | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number
  name: string
  /**
   * Généré depuis le nom, utilisé dans les URL de filtre.
   */
  slug?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * Collez l'URL : le reste est récupéré automatiquement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: number
  /**
   * Normalisée automatiquement : les paramètres de suivi sont retirés.
   */
  url: string
  /**
   * Laissez vide pour reprendre le titre de la page distante.
   */
  title?: string | null
  /**
   * Laissez vide pour reprendre la description de la page distante.
   */
  description?: string | null
  /**
   * Déduit de l'URL, utilisé pour l'affichage et le favicon.
   */
  domain?: string | null
  /**
   * Extraite des balises Open Graph à chaque modification de l'URL.
   */
  previewImageUrl?: string | null
  /**
   * Sert aux filtres de la page Veille.
   */
  tags?: (number | Tag)[] | null
  /**
   * Décochez pour retirer le lien du site sans le supprimer.
   */
  active?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'projects'
        value: number | Project
      } | null)
    | ({
        relationTo: 'experiences'
        value: number | Experience
      } | null)
    | ({
        relationTo: 'tags'
        value: number | Tag
      } | null)
    | ({
        relationTo: 'bookmarks'
        value: number | Bookmark
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  url?: T
  title?: T
  description?: T
  previewImageUrl?: T
  cover?: T
  repositoryUrl?: T
  technologies?: T
  featured?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  company?: T
  role?: T
  location?: T
  startDate?: T
  endDate?: T
  current?: T
  project?: T
  context?: T
  achievements?:
    | T
    | {
        statement?: T
        id?: T
      }
  technologies?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  url?: T
  title?: T
  description?: T
  domain?: T
  previewImageUrl?: T
  tags?: T
  active?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * Coordonnées, liens sociaux et informations légales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity".
 */
export interface SiteIdentity {
  id: number
  contact: {
    /**
     * Nom montré sur le site et dans les titres de page. L'identité légale complète se saisit dans « Éditeur », plus bas.
     */
    displayName: string
    role: string
    /**
     * Affichée dans le pied de page et sur la page À propos.
     */
    location?: string | null
    email: string
  }
  social?: {
    githubUrl?: string | null
    linkedinUrl?: string | null
  }
  /**
   * Sert à générer la page Mentions légales.
   */
  legal?: {
    /**
     * Personne physique ou morale responsable de la publication. La loi exige ici une identité complète : nom et prénom pour un particulier. Seule cette page l’affiche, le reste du site utilise le nom d’affichage.
     */
    publisher?: string | null
    hostName?: string | null
    hostAddress?: string | null
    /**
     * Ce que le site collecte, et ce qu’il n’en fait pas.
     */
    dataPolicy?: string | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Biographie, compétences et principes affichés sur la page À propos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number
  headline: string
  /**
   * Deux à trois phrases, à la première personne.
   */
  bio: string
  /**
   * Seul chiffre affiché en haut de page. Laissez vide pour le masquer.
   */
  yearsOfExperience?: number | null
  skillGroups?:
    | {
        label: string
        items: string[]
        id?: string | null
      }[]
    | null
  principles?:
    | {
        statement: string
        /**
         * Optionnel : ce que le principe change concrètement.
         */
        detail?: string | null
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-identity_select".
 */
export interface SiteIdentitySelect<T extends boolean = true> {
  contact?:
    | T
    | {
        displayName?: T
        role?: T
        location?: T
        email?: T
      }
  social?:
    | T
    | {
        githubUrl?: T
        linkedinUrl?: T
      }
  legal?:
    | T
    | {
        publisher?: T
        hostName?: T
        hostAddress?: T
        dataPolicy?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  headline?: T
  bio?: T
  yearsOfExperience?: T
  skillGroups?:
    | T
    | {
        label?: T
        items?: T
        id?: T
      }
  principles?:
    | T
    | {
        statement?: T
        detail?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
